apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-webhook-deployment
  namespace: sms-webhook
  labels:
    app: sms-webhook
spec:
  replicas: 1  # 测试先用 1 个
  selector:
    matchLabels:
      app: sms-webhook
  template:
    metadata:
      labels:
        app: sms-webhook
    spec:
      containers:
      - name: sms-webhook
        image: 10.29.230.150:31381/library/sms-test:20251031-1
        ports:
        - containerPort: 8080
        env:
        - name: SMS_API_URL
          value: "http://fake-sms.sms-webhook.svc.cluster.local:9999/sms"
        - name: SMS_CODE
          value: "ALERT_CODE"
        - name: SMS_TARGET
          value: "15222222222"
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: sms-webhook-service
  namespace: sms-webhook
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sms-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: fake-sms
  namespace: sms-webhook
spec:
  selector:
    app: fake-sms
  ports:
    - port: 9999
      targetPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-sms
  namespace: sms-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-sms
  template:
    metadata:
      labels:
        app: fake-sms
    spec:
      containers:
        - name: fake-sms
          image: 10.29.230.150:31381/library/ealen/echo-server:0.9.2
          env:
            - name: PORT
              value: "9999"
          ports:
            - containerPort: 9999
