apiVersion: v1
kind: Namespace
metadata:
  name: sms-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-webhook-deployment
  namespace: sms-webhook
  labels:
    app: sms-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-webhook
  template:
    metadata:
      labels:
        app: sms-webhook
    spec:
      containers:
      - name: sms-webhook
        image: 10.29.230.150:31381/library/sms-test:20251103
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "debug"
        - name: SMS_API_URL
          value: "http://fake-sms.sms-webhook.svc.cluster.local:9999/json"
        - name: SMS_CODE
          value: "ALERT_CODE"
        - name: SMS_TARGET
          value: "15222222222"
        - name: SMS_PROVIDER
          value: "json"
        # 默认只发一条
        - name: SMS_SEND_MODE
          value: "pick"
        # 一次性配三种：json / form / header-json
        - name: SMS_PROVIDERS_JSON
          value: |-
            [
              {
                "name": "json",
                "kind": "json",
                "url": "http://fake-sms.sms-webhook.svc.cluster.local:9999/json",
                "code": "ALERT_CODE"
              },
              {
                "name": "header",
                "kind": "header-json",
                "url": "http://fake-sms.sms-webhook.svc.cluster.local:9999/header",
                "code": "ALERT_CODE",
                "api_key": "abc123",
                "header_key": "X-API-KEY"
              },
              {
                "name": "form",
                "kind": "form",
                "url": "http://fake-sms.sms-webhook.svc.cluster.local:9999/form",
                "code": "FORM_CODE",
                "phone_field": "target",
                "content_field": "content",
                "code_field": "code"
              },
              {
              "name": "feishu",
              "kind": "feishu",
              "url": "https://open.feishu.cn/open-apis/bot/v2/hook/d46d8ce4-e298-4894-b5da-37ad2613104c",
              "secret": "T1dgjnnwepkB2JrlhawRke"
            }
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: sms-webhook-service
  namespace: sms-webhook
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30127
  selector:
    app: sms-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-sms
  namespace: sms-webhook
  labels:
    app: fake-sms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-sms
  template:
    metadata:
      labels:
        app: fake-sms
    spec:
      containers:
        - name: fake-sms
          image: 10.29.230.150:31381/library/ealen/echo-server:0.9.2
          env:
            - name: PORT
              value: "9999"
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: fake-sms
  namespace: sms-webhook
spec:
  selector:
    app: fake-sms
  ports:
    - port: 9999
      targetPort: 9999
